relay: Make SSL certificate/key loading error handling more verbose
weechat/weechat pull request #1558
Opened 2020-09-14 22:35 UTC by NP-Hardass

2020-10-11 15:49 UTC, flashcode commented
Hi,
Could you please update your commit and change only source code files, not translations (they're updated later and could cause conflicts like now)?
Thanks.

2020-12-17 16:50 UTC, NP-Hardass commented
@flashcode is there something else you need from me regarding this patch?

2021-01-07 07:19 UTC, flashcode requested changes

2021-01-07 07:19 UTC, flashcode commented on src/plugins/relay/relay-network.c
>              free (certkey_path2);
In the else clause, this variable is not freed.
You should move this block after the else block and replace it with:

```C
    if (certkey_path2)
        free (certkey_path2);
```

2023-05-18 07:52 UTC, closed without merging

2023-05-18 07:55 UTC, flashcode commented
Thanks, merged, with some changes, and adapted the code to the latest version (options "ssl" have been renamed to "tls" in 4.0.0).