add spanish translations to some sentences
weechat/weechat pull request #1691
Opened 2021-09-08 02:24 UTC by forerosantiago

Hey, I translated a lot of sentences to Spanish (:

2021-09-08 16:01 UTC, flashcode requested changes
Hi,

Thanks for the update on translations.
There are some errors (see my comments), and please ensure the file is OK using https://github.com/flashcode/msgcheck.

2021-09-08 20:35 UTC, forerosantiago commented
All right @flashcode, I corrected the mistakes you pointed and checked the po file with msgcheck, the file is OK.

2021-09-10 22:17 UTC, flashcode commented
Hi,

Thanks for changes.

Many "fuzzy" markers are still there on translations you updated, you must remove them if the translation is done, otherwise the translation is not used at all (considered wrong or approximative, so English is used instead).

Also could you please rebase your branch on master, by merging your changes with the latest changes in WeeChat? (maybe using command `msgmerge`), because now there are conflicts.

2021-09-13 12:46 UTC, forerosantiago commented
All right, Iremoved several fuzzy markers and tried to fix the conflicts, can you please confirm if I fixed the conflicts correctly?

2021-09-13 12:46 UTC, forerosantiago commented
Oops, accidentally closed.

2021-09-26 21:12 UTC, flashcode commented on po/es.po
>  #, fuzzy
Hi,
Some translations are still marked as "fuzzy" but translated, you must remove this fuzzy marker (multiple places).
Thanks.

2021-11-07 23:37 UTC, forerosantiago commented
Hello @flashcode, I fixed the errors and made a commit a few days ago. Just reminding you about it in case you missed it.

Cheers!

2021-11-08 19:22 UTC, flashcode approved these changes

2021-11-08 19:26 UTC, flashcode commented
Thanks, I upported your changes on the master branch and committed your changes.

2021-11-08 19:26 UTC, closed without merging