javascript eval function
weechat/weechat pull request #1850
Opened 2022-11-11 13:51 UTC by reyesjl

implemented the JavaScript eval function

2022-12-11 14:31 UTC, flashcode requested changes

2023-03-23 14:16 UTC, reyesjl commented on src/plugins/javascript/weechat-js.cpp
> +char **js_buffer_output = NULL;
hmm, I see - will update tonight.

2023-03-23 14:18 UTC, reyesjl reviewed
Looks good to me.

2023-03-26 20:39 UTC, flashcode commented
Hi,
Did you push your changes?
I don't see any changes in the commit.

2023-03-27 14:23 UTC, reyesjl commented
Sebastien,

I did not. Which variable must I get rid of? - I was having trouble reading the information request and understanding which line or variable it was referring to do you think you can help me out in identifying this?

Thank you,
Jose

________________________________
From: Sébastien Helleu ***@***.***>
Sent: Sunday, March 26, 2023 4:39 PM
To: weechat/weechat ***@***.***>
Cc: jose reyes ***@***.***>; Author ***@***.***>
Subject: Re: [weechat/weechat] javascript eval function (PR #1850)


Hi,
Did you push your changes?
I don't see any changes in the commit.

—
Reply to this email directly, view it on GitHub<https://github.com/weechat/weechat/pull/1850#issuecomment-1484216487>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AI6GQ4Q3EPJVVVISEGN2XWDW6CZRXANCNFSM6AAAAAAR5TY424>.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-03-27 17:31 UTC, trygveaa commented
> Sebastien, I did not. Which variable must I get rid of? - I was having trouble reading the information request and understanding which line or variable it was referring to do you think you can help me out in identifying this?

It's the `js_buffer_output` variable.

Did you compile this code? I'm getting these compilation errors when I try:

```
/home/trygve/dev/weechat/src/plugins/javascript/weechat-js.cpp: In function ‘void weechat_js_output_flush()’:
/home/trygve/dev/weechat/src/plugins/javascript/weechat-js.cpp:210:34: error: invalid conversion from ‘void*’ to ‘char*’ [-fpermissive]
  210 |                 command = malloc (length);
      |                           ~~~~~~~^~~~~~~~
      |                                  |
      |                                  void*
/home/trygve/dev/weechat/src/plugins/javascript/weechat-js.cpp: In function ‘int weechat_js_eval(t_gui_buffer*, int, int, const char*)’:
/home/trygve/dev/weechat/src/plugins/javascript/weechat-js.cpp:635:26: error: expected unqualified-id before ‘int’
  635 |     void *func_argv[1], *int result;
      |                          ^~~
/home/trygve/dev/weechat/src/plugins/javascript/weechat-js.cpp:641:41: error: ‘JS_EVAL_SCRIPT’ was not declared in this scope
  641 |                                         JS_EVAL_SCRIPT);
      |                                         ^~~~~~~~~~~~~~
/home/trygve/dev/weechat/src/plugins/javascript/weechat-js.cpp:655:5: error: ‘result’ was not declared in this scope
  655 |     result = weechat_js_exec (js_script_eval,
      |     ^~~~~~
make[2]: *** [src/plugins/javascript/CMakeFiles/javascript.dir/build.make:76: src/plugins/javascript/CMakeFiles/javascript.dir/weechat-js.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1698: src/plugins/javascript/CMakeFiles/javascript.dir/all] Error 2
```

2023-06-10 00:26 UTC, reyesjl commented
hmm I apologize, I don't think I will be able to complete this.

2023-06-10 00:26 UTC, closed without merging