Add /api/completion route
weechat/weechat pull request #2207
Opened 2024-11-02 12:00 UTC by nilscc

Added route handler for `/api/completion`. Open tasks:

* Update documentation
* Update API specification yaml file

Let's first discuss the implementation. 🙂

2024-11-03 16:17 UTC, nilscc commented on src/plugins/relay/api/relay-api-protocol.c
> +                    RELAY_HTTP_400_BAD_REQUEST, NULL,
400 seems like the correct response, as the route is available (i.e. not 404), but the buffer ID is invalid. this is inconsistent with the handling of the `/api/input` handler (line 849+) though => change input route as well?

2024-11-04 17:01 UTC, nilscc commented on src/plugins/relay/api/relay-api-protocol.c
> +                    RELAY_HTTP_400_BAD_REQUEST, NULL,
Done.

2024-11-24 16:54 UTC, flashcode requested changes

2024-11-24 16:54 UTC, flashcode commented on tests/unit/plugins/relay/api/test-relay-api-msg.cpp
> +    cJSON *json; //, *json_obj, *json_count;
It seems this test is not complete, and some commented variables are still there.
Please make a complete test by building a completion JSON object with a real completion.

You should be able to simulate a completion from user on core buffer with such code:

```C
gui_buffer_set (gui_buffers, "input", "/co"); 
gui_buffer_set (gui_buffers, "input_pos", "3");
gui_input_complete_next (gui_buffers);
```

2025-01-05 14:08 UTC, flashcode commented
Thanks, I merged with some changes:

- code style changes
- add completion context "null" (should happen rarely, but can be returned by the API) and defaults to "auto" if unknown (same as the "weechat" protocol)
- rename body field "data" to "command" (to be consistent with `POST /api/input`)
- return `RELAY_API_PROTOCOL_RC_MEMORY` when the completion can not be created (instead of "bad request")
- update OpenAPI spec YAML document (file `weechat-relay-api.yaml`)
- bump relay API version
- add missing include of header and fix unit tests

2025-01-05 14:08 UTC, closed without merging